### ISSUE TITLE
oracle number fields and EsHadoopSerializationException: Decimal types are not supported by Elasticsearch

### ISSUE THREAD

**Issue by pirat8** [kohesive/elasticsearch-data-import-handler#34]
Hi,

when I include a field of type NUMBER in my oracle export statement I get the following exception:

`Job aborted due to stage failure: Task 0 in stage 0.0 failed 1 times, most recent failure: Lost task 0.0 in stage 0.0 (TID 0, localhost, executor driver): org.elasticsearch.hadoop.serialization.EsHadoopSerializationException: Decimal types are not supported by Elasticsearch - consider using a different type (such as string)
	at org.elasticsearch.spark.sql.DataFrameValueWriter.writePrimitive(DataFrameValueWriter.scala:180)
	at org.elasticsearch.spark.sql.DataFrameValueWriter.write(DataFrameValueWriter.scala:106)
	at org.elasticsearch.spark.sql.DataFrameValueWriter$$anonfun$writeStruct$1.apply(DataFrameValueWriter.scala:85)
	at org.elasticsearch.spark.sql.DataFrameValueWriter$$anonfun$writeStruct$1.apply(DataFrameValueWriter.scala:80)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableViewLike$Transformed$class.foreach(IterableViewLike.scala:44)
	at scala.collection.SeqViewLike$AbstractTransformed.foreach(SeqViewLike.scala:37)
	at org.elasticsearch.spark.sql.DataFrameValueWriter.writeStruct(DataFrameValueWriter.scala:80)
	at org.elasticsearch.spark.sql.DataFrameValueWriter.write(DataFrameValueWriter.scala:72)
	at org.elasticsearch.spark.sql.DataFrameValueWriter.write(DataFrameValueWriter.scala:54)
	at org.elasticsearch.hadoop.serialization.builder.ContentBuilder.value(ContentBuilder.java:53)
	at org.elasticsearch.hadoop.serialization.bulk.TemplatedBulk.doWriteObject(TemplatedBulk.java:71)
	at org.elasticsearch.hadoop.serialization.bulk.TemplatedBulk.write(TemplatedBulk.java:58)
	at org.elasticsearch.hadoop.rest.RestRepository.writeToIndex(RestRepository.java:159)
	at org.elasticsearch.spark.rdd.EsRDDWriter.write(EsRDDWriter.scala:67)
	at org.elasticsearch.spark.sql.EsSparkSQL$$anonfun$saveToEs$1.apply(EsSparkSQL.scala:91)
	at org.elasticsearch.spark.sql.EsSparkSQL$$anonfun$saveToEs$1.apply(EsSparkSQL.scala:91)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`
How to export non-string fields?

When I do something like 
` "sqlQuery": """
     SELECT TO_CHAR(ID), ... FROM ...
  """
`
I get a
`
Caused by: org.apache.spark.sql.AnalysisException: Undefined function: 'TO_CHAR'. This function is neither a registered temporary function nor a permanent function registered in the database 'default'.; line 2 pos 19
`
exception.

May be it has something to do with:
https://issues.apache.org/jira/browse/SPARK-10909
but this issue is resolved...

**Comment by apatrida** [comment]
What version of the data import handler are you using?  (just so I know which Spark version is inside)

**Comment by apatrida** [comment]
And I don't think that SPARK-10909 is related.  I'll check into this...

**Comment by apatrida** [comment]
This explains the issue:  https://github.com/elastic/elasticsearch-hadoop/issues/842

So if you cast it to a string, and then let Elasticsearch later do the conversion to whatever numeric type you picked in the mappings (odd, they block the precision loss earlier, but then do it later).

And to change the type, you want to stay with Spark SQL functions, not Oracle.  You are coding in the uniform non-database specific SQL, so it would be something like:

```
SELECT cast(something as String) AS something
   FROM myTable
```

or cast to an integer type if it is not really a decimal value.

**Comment by pirat8** [comment]
Hi,

I use: kohesive-es-dih-0.9.0-ALPHA

I observed another problem:
Because I got problems with the number fields I applied a SELECT which only uses
string fields.

Here is my conf-file
>snip
{
  "sources": {
    "jdbc": [
      {
        "jdbcUrl": "jdbc:oracle:thin:@...",
        "driverClass": "oracle.jdbc.driver.OracleDriver",
        "defaultSchema": "cobra",
        "auth": {
          "username": "XXX",
          "password": "XXX"
        },
        "driverJars": ["../lib/ojdbc6.jar"],  # MySQL and Postgres JARS are included automatically, this property can be omitted completely
        "tables": [
          {
            "sparkTable": "OHRDRUF_BESTAND",
            "sourceTable": "SOLAR_STOCK_EXTRACTOR_WHS_V08"
          }
        ]
      }
    ]
  },
  "importSteps": [
    {
      "description": "Data loaders for base data sets",
      "targetElasticsearch": {
        "nodes": [
          "localhost:9200"
        ],
        "settings": {
          "es.index.auto.create": true
        }
      },
      "statements": [
        {
          "id": "Q4499_1234",
          "description": "Load Ohrdruf Bestand data into ES",
          "indexName": "ohrdruf",
          "indexType": "bestand",
          "settings": {
            "es.mapping.id": "uuid"
          },
          "sqlQuery": """
                SELECT s.firma_nr from OHRDRUF_BESTAND s where s.lager_id=8 and s.firma_nr=6
          """
        }
      ]
    }
  ]
}
>snip

SOLAR_STOCK_EXTRACTOR_WHS_V08 is a view in a database and firma_nr is a field of type string.
When I run this I get:

org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 1 times, most recent failure: Lost task 0.0 in stage 0.0 (TID 0, localhost, executor driver): java.sql.SQLException: Protokollverletzung
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:450)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:186)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:521)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:205)
	at oracle.jdbc.driver.T4CPreparedStatement.fetch(T4CPreparedStatement.java:1082)
	at oracle.jdbc.driver.OracleResultSetImpl.close_or_fetch_from_next(OracleResultSetImpl.java:369)
	at oracle.jdbc.driver.OracleResultSetImpl.next(OracleResultSetImpl.java:273)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$$anon$1.getNext(JdbcUtils.scala:282)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$$anon$1.getNext(JdbcUtils.scala:268)
	at org.apache.spark.util.NextIterator.hasNext(NextIterator.scala:73)
	at org.apache.spark.util.CompletionIterator.hasNext(CompletionIterator.scala:32)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:377)
	at org.apache.spark.sql.execution.columnar.InMemoryRelation$$anonfun$1$$anon$1.next(InMemoryRelation.scala:105)
	at org.apache.spark.sql.execution.columnar.InMemoryRelation$$anonfun$1$$anon$1.next(InMemoryRelation.scala:97)
	at org.apache.spark.storage.memory.MemoryStore.putIteratorAsValues(MemoryStore.scala:216)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:957)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:948)
	at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:888)
	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:948)
	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:694)
	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:334)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:285)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
>snip

SOLAR_STOCK_EXTRACTOR_WHS_V08 is a view in the oracle database.

The SELECT -->
"SELECT s.firma_nr from OHRDRUF_BESTAND s where s.lager_id=8 and s.firma_nr=6"
should return only 320 records.
However kohesive-es-dih runs some minutes until it dies with the exception above.

In reality we have to import a lot of data. We are looking for a importing tool for ES
similar dast as DIH for solr. 

Thank you for your quick response. I'm happy about every hint about this. All this solr/ES stuff
is quite new to me.

Thomas

**Comment by apatrida** [comment]
Can you make this a separate issue in the tracker, otherwise it gets confusing to other's that read these issues and also makes it hard to track if a closed issue gets comments on another topic.    You can remove the comment here, and create a new issue and I'll see it just as quickly.
