### ISSUE TITLE
oracle import and java.sql.SQLException: Protokollverletzung

### ISSUE THREAD

**Issue by pirat8** [kohesive/elasticsearch-data-import-handler#35]
Hi,
I use: kohesive-es-dih-0.9.0-ALPHA
I observed the following problem with a oracle database:

Because I got problems with the number fields I applied a SELECT which only uses string fields.

Here is my conf-file
>snip
{
"sources": {
"jdbc": [
{
"jdbcUrl": "jdbc:oracle:thin:@...",
"driverClass": "oracle.jdbc.driver.OracleDriver",
"defaultSchema": "XXX",
"auth": {
"username": "XXX",
"password": "XXX"
},
"driverJars": ["../lib/ojdbc6.jar"], # MySQL and Postgres JARS are included automatically, this property can be omitted completely
"tables": [
{
"sparkTable": "OHRDRUF_BESTAND",
"sourceTable": "SOLAR_STOCK_EXTRACTOR_WHS_V08"
}
]
}
]
},
"importSteps": [
{
"description": "Data loaders for base data sets",
"targetElasticsearch": {
"nodes": [
"localhost:9200"
],
"settings": {
"es.index.auto.create": true
}
},
"statements": [
{
"id": "Q4499_1234",
"description": "Load Ohrdruf Bestand data into ES",
"indexName": "ohrdruf",
"indexType": "bestand",
"settings": {
"es.mapping.id": "uuid"
},
"sqlQuery": """
SELECT s.firma_nr from OHRDRUF_BESTAND s where s.lager_id=8 and s.firma_nr=6
"""
}
]
}
]
}
>snip

SOLAR_STOCK_EXTRACTOR_WHS_V08 is a view in a database and firma_nr is a field of type string.
When I run this I get:

org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 1 times, most recent failure: Lost task 0.0 in stage 0.0 (TID 0, localhost, executor driver): java.sql.SQLException: Protokollverletzung
at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:450)
at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:186)
at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:521)
at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:205)
at oracle.jdbc.driver.T4CPreparedStatement.fetch(T4CPreparedStatement.java:1082)
at oracle.jdbc.driver.OracleResultSetImpl.close_or_fetch_from_next(OracleResultSetImpl.java:369)
at oracle.jdbc.driver.OracleResultSetImpl.next(OracleResultSetImpl.java:273)
at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$$anon$1.getNext(JdbcUtils.scala:282)
at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$$anon$1.getNext(JdbcUtils.scala:268)
at org.apache.spark.util.NextIterator.hasNext(NextIterator.scala:73)
at org.apache.spark.util.CompletionIterator.hasNext(CompletionIterator.scala:32)
at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:377)
at org.apache.spark.sql.execution.columnar.InMemoryRelation$$anonfun$1$$anon$1.next(InMemoryRelation.scala:105)
at org.apache.spark.sql.execution.columnar.InMemoryRelation$$anonfun$1$$anon$1.next(InMemoryRelation.scala:97)
at org.apache.spark.storage.memory.MemoryStore.putIteratorAsValues(MemoryStore.scala:216)
at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:957)
at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:948)
at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:888)
at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:948)
at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:694)
at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:334)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:285)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
at org.apache.spark.scheduler.Task.run(Task.scala:99)
at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
>snip

SOLAR_STOCK_EXTRACTOR_WHS_V08 is a view in the oracle database.

The SELECT -->
"SELECT s.firma_nr from OHRDRUF_BESTAND s where s.lager_id=8 and s.firma_nr=6"
should return only 320 records.
However kohesive-es-dih runs some minutes until it dies with the exception above.

**Comment by apatrida** [comment]
This is an Oracle JDBC driver error (or an error caused by not enough memory making the driver fail).  Based on my Googling of "[oracle jdbc Protokollverletzung](https://www.google.com/search?q=oracle+jdbc+Protokollverletzung)" the results shows a lot of information about this.

You should:

1.  Check that the SQL is returning the number of rows you think it is
2.  Check that you aren't doing something known to cause this protocol violation problem
3.  Check the memory you have given to Elasticsearch Data Import Handler, see docs: https://github.com/kohesive/elasticsearch-data-import-handler#memory-issues
4.  Check you have latest version of Oracle JDBC driver that is compatible with your version of Oracle

On a side note, instead of having a view convert everything to char types, I would go back to your original SQL and just use `cast(somethingDecimal as String) AS somethingDecimal` so that you are only doing the ETL stuff within the query and not creating a view to do it.  But you can still try to resolve this issue as-is.

**Comment by apatrida** [comment]
as a side note:

Here in Github, you can place your stack traces and code snippets within blocks demarcated by triple back ticks:  ```  

This would look like:

````
``` 
   code or stacktrace
```
````

That will preserve indentation / formatting and also add syntax highlighting if it is code.  Easier to read :-D

**Comment by apatrida** [comment]
Please note that a full load in data import handler will load all data into memory, since that is what Spark does.  So you must allocate enough memory for your full load to handle that.  Incremental loads can use a lot less memory since they are based on a smaller set of records that changed since the last load.  Later we will be adding a streaming model to load data as batches so that this is not a requirement, but typically people are using this with small sets that are OK to be in memory, or against a Spark cluster to process ETL on millions of rows and then they are again OK due to having a cluster.  That is why you should check the items listed above, that you aren't pulling in a million rows but not giving the Java VM enough memory to handle that.

**Comment by apatrida** [comment]
Note:  I'll be releasing another version later today that lowers memory by removing the caching of the main query by default (which is set to MEMORY_ONLY which might overflow memory), otherwise it would just spill to disk if needed as Spark normally does.  I also added a persist setting for more control of this cache step if desired.  I'll release this later today, but I don't think this is related to your issue unless you are just really memory constrained (which should be giving a different error, or at least lower down in your stack trace showing an Out Of Memory exception if that was the case).

**Comment by apatrida** [comment]
v0.10.0-ALPHA has been released which lowers memory use by default with no more forced caching of the result into memory, you can see the changes in the README about caching if you want to enable a memory or memory+disk cache based on what you wish to have happen.

**Comment by pirat8** [comment]
Hi,
I tested the new version with my large oracle view. In contrast to 0.9.0 the program did not die with an exception but the import is far too slow. I compare it with the DataImportHandler from solr.
My question: Does kohesive-es-dih use the REST-API of elasticsearch or does it write straightforward  a "core-file" to the file system?
