### ISSUE TITLE
State manager failed, cannot create state index

### ISSUE THREAD

**Issue by gvsrini** [kohesive/elasticsearch-data-import-handler#42]
Any pointers on how to solve this issue:

```
Kohesive - Elasticsearch Data Import Utility
Connecting to target ES/Algolia to check state...
Data import failed due to:
State manager failed, cannot create state index
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Rejecting mapping update to [.kohesive-dih-state-v2] as the final mapping would have more than 1 type: [log, lock, state]"}],"type":"illegal_argument_exception","reason":"Rejecting mapping update to [.kohesive-dih-state-v2] as the final mapping would have more than 1 type: [log, lock, state]"},"status":400}

Debug stack trace:
uy.kohesive.elasticsearch.dataimport.DataImportException: State manager failed, cannot create state index
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Rejecting mapping update to [.kohesive-dih-state-v2] as the final mapping would have more than 1 type: [log, lock, state]"}],"type":"illegal_argument_exception","reason":"Rejecting mapping update to [.kohesive-dih-state-v2] as the final mapping would have more than 1 type: [log, lock, state]"},"status":400}
        at uy.kohesive.elasticsearch.dataimport.ElasticSearchStateManager.init(State.kt:71)
        at uy.kohesive.elasticsearch.dataimport.App.run(App.kt:88)
        at uy.kohesive.elasticsearch.dataimport.App$Companion.main(App.kt:40)
        at uy.kohesive.elasticsearch.dataimport.App.main(App.kt)
```

**Comment by apatrida** [comment]
It looks like your version of Elasticsearch is newer than what is supported.  I will do an update soon to current versions of Elasticsearch.
